### ISSUE TITLE
GOT SIGTERM, shutting down home bridge issue

### ISSUE THREAD

**Issue by jfinestone** [senorshaun/homebridge-radiora2#12]
Added a keypad to my previously working radiora1/homebridge integration. and then this started...

[12/30/2021, 9:31:21 AM] TypeError: Cannot read properties of undefined (reading 'toString')
    at new KeypadButton (/homebridge/node_modules/homebridge-radiora2/lib/accessories/keypadbutton.js:15:72)
    at RadioRA2Platform.addKeypadButtonAccessory (/homebridge/node_modules/homebridge-radiora2/index.js:141:44)
    at RadioRA2Platform.<anonymous> (/homebridge/node_modules/homebridge-radiora2/index.js:281:34)
    at Array.forEach (<anonymous>)
    at RadioRA2Platform.<anonymous> (/homebridge/node_modules/homebridge-radiora2/index.js:272:26)
    at RadioRa2.emit (node:events:390:28)
    at incomingData (/homebridge/node_modules/homebridge-radiora2/lib/radiora2.js:97:20)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-radiora2/lib/radiora2.js:27:92)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
[12/30/2021, 9:31:21 AM] [Hubitat-v2] Temperature Unit is Now: (F)
[12/30/2021, 9:31:21 AM] [Hubitat-v2] Updating Global Values | HubIP: 10.100.10.28 | UsingCloud: false
[12/30/2021, 9:31:21 AM] [Hubitat-v2] Devices to Remove: (0) 
[12/30/2021, 9:31:21 AM] [Hubitat-v2] Devices to Update: (4)
[12/30/2021, 9:31:21 AM] [Hubitat-v2] Devices to Create:
[12/30/2021, 9:31:41 AM] Got SIGTERM, shutting down Homebridge...
[12/30/2021, 9:31:41 AM] [RadioRA2] Disconnecting

**Comment by senorshaun** [comment]
the button isn't named in your config. handled with the pull request which makes those optional

**Comment by jfinestone** [comment]
Thank you for the prompt response. Can you explain a little further I don’t
see where I had to name it and I’m not exactly sure what a pull request is
or how to use that.

Thanks.

**Comment by senorshaun** [comment]
I just published 1.3.4 to npm. update your copy of the plugin. @cariacou modified some code to make parameters, like the name of buttons, optional.
here's an example config where it shows buttons and keypads using names
`"keypads": [
                        {
                                "name": "Lutron Buttons",
                                "id": 1,
                                "model": "RR-MAIN-REP-WH",
                                "serial": "xxxxxxxxx",
                                "stateless": false,
                                "buttons":[
                                        {
                                                "name": "Normal Light Level",
                                                "id": 1,
                                                "led": 101
                                        },
                                        {
                                                "name": "Low Light Level",
                                                "id": 2,
                                                "led": 102
                                        },
...`
