### ISSUE TITLE
cannot autofind devices

### ISSUE THREAD

**Issue by oxide7** [senorshaun/homebridge-radiora2#41]
When I try to autofind my devices the icon just spins. I let it run over night to no avail.

When I enable the logs I see PING! 4 times a second, but see these interspersed from time to time:
[1/16/2024, 10:01:24 AM] [RadioRA2] PING!
[1/16/2024, 10:01:24 AM] [RadioRA2] IP packet has my MAC address, but wrong IP address
[1/16/2024, 10:01:24 AM] [RadioRA2] PING!
[1/16/2024, 10:01:24 AM] [RadioRA2] PING!
and
[1/16/2024, 10:01:27 AM] [RadioRA2] PING!
[1/16/2024, 10:01:28 AM] [RadioRA2] Diag Error On Line 413 of dns_private.cpp
[1/16/2024, 10:01:28 AM] [RadioRA2] Didn't find A record response in DNS response
[1/16/2024, 10:01:28 AM] [RadioRA2] PING!
and
[1/16/2024, 10:01:55 AM] [RadioRA2] ~HVAC,106,14,1
[1/16/2024, 10:01:55 AM] [RadioRA2] PING!

I dont know what the user/pass is but when i use the default one i see this activity. When i use something known to be wrong there are no pings, so i assume the default one is working.

please advise

**Comment by senorshaun** [comment]
Was your system created with the Lutron software? Or a walk around programming, where you just put the repeater in sync mode and sync each device?
the necessary file is only created on the repeater if the software is used. 

In a web browser, try to go to https://<ipaddress_of_repeater>/DbXmlInfo.xml and see if you get anything back. If not, auto discover will not work for you

**Comment by oxide7** [comment]
I'm pretty sure it was done with software. see attatched xml from the link you suggested. 
[DbXmlInfo.xml.zip](https://github.com/senorshaun/homebridge-radiora2/files/14074254/DbXmlInfo.xml.zip)

**Comment by senorshaun** [comment]
Yeah it has the file needed. Do you have two devices using the same IP address? 
Do the logs from your first post only show up when you do the auto-discovery? or the entire time the plugin is running?

**Comment by oxide7** [comment]
It seems to do that even when i do not have discovery on. I see all of what i posted above, except the "HVAC" line.....

**Comment by oxide7** [comment]
If it makes this any easier, I do have a lutron bridge, but it doesnt exposr the ceiling fans or the hvac (and associated temperatures) controls around the house to Homekit. I was hoping that with this plug in, I can expose everything, though I really just need those items. The lutron app has everything but of course i want it all in homekit.

**Comment by senorshaun** [comment]
What IP address are you pointing this plugin at? The repeater or bridge? With this plugin, you don’t need the bridge. That could be the issue?On Jan 27, 2024, at 8:04 PM, oxide7 ***@***.***> wrote:﻿
If it makes this any easier, I do have a lutron bridge, but it doesnt exposr the ceiling fans or the hvac (and associated temperatures) controls around the house to Homekit. I was hoping that with this plug in, I can expose everything, though I really just need those items. The lutron app has everything but of course i want it all in homekit.

**Comment by oxide7** [comment]
its definately pointed at the actual lutron thing, not the bridge. That is where i got the XML from also

**Comment by oxide7** [comment]
are you able to manually make a config file from the xml i gave you, if the tool will not make it automatically?

**Comment by senorshaun** [comment]
I just published 1.7.5 that may fix the issue

**Comment by oxide7** [comment]
not sure why you would close the bug without confirming its fix. 1.75 gives me this:
[2/4/2024, 8:37:10 PM] [RadioRA2] PING!
[2/4/2024, 8:37:11 PM] [RadioRA2] PING!
[2/4/2024, 8:37:12 PM] [RadioRA2] PING!
[2/4/2024, 8:37:13 PM] [RadioRA2] PING!
[2/4/2024, 8:37:13 PM] [Homebridge UI] [homebridge-radiora2] TypeError: areas.hasOwnProperty is not a function
    at UiServer.processAreas (/homebridge/node_modules/homebridge-radiora2/homebridge-ui/server.js:27:14)
    at /homebridge/node_modules/homebridge-radiora2/homebridge-ui/server.js:245:64
    at Array.map (<anonymous>)
    at UiServer.getAllDevices (/homebridge/node_modules/homebridge-radiora2/homebridge-ui/server.js:245:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UiServer.processRequest (/homebridge/node_modules/homebridge-radiora2/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)
[2/4/2024, 8:37:14 PM] [RadioRA2] PING!
[2/4/2024, 8:37:15 PM] [RadioRA2] PING!
[2/4/2024, 8:37:16 PM] [RadioRA2] PING!
[2/4/2024, 8:37:17 PM] [RadioRA2] PING!
[2/4/2024, 8:37:18 PM] [RadioRA2] PING!
[2/4/2024, 8:37:19 PM] [RadioRA2] PING!

**Comment by oxide7** [comment]
something did come out after about an hour: This ist he first time ive seen this. is it a slow process? It's still going but no conlcusion yet 
[2/4/2024, 8:53:39 PM] [RadioRA2] PING!
[2/4/2024, 8:53:40 PM] [RadioRA2] PING!
[2/4/2024, 8:53:41 PM] [RadioRA2] PING!
[2/4/2024, 8:53:42 PM] [RadioRA2] PING!
[2/4/2024, 8:53:43 PM] [RadioRA2] PING!
[2/4/2024, 8:53:44 PM] [RadioRA2] ~DEVICE,120,2,3
[2/4/2024, 8:53:44 PM] [RadioRA2] ~ADDRESS,0x007FD226
[2/4/2024, 8:53:44 PM] [RadioRA2] Preset ID:     4104 does not pertain to a device on link 0. Do nothing
[2/4/2024, 8:53:44 PM] [RadioRA2] ~OUTPUT,98,1,90.00
[2/4/2024, 8:53:44 PM] [RadioRA2] ~OUTPUT,98,29,8
[2/4/2024, 8:53:44 PM] [RadioRA2] ~OUTPUT,98,30,1,90.00
[2/4/2024, 8:53:44 PM] [RadioRA2] ~OUTPUT,99,1,90.00
[2/4/2024, 8:53:44 PM] [RadioRA2] ~OUTPUT,99,29,8
[2/4/2024, 8:53:44 PM] [RadioRA2] ~OUTPUT,99,30,1,90.00
[2/4/2024, 8:53:44 PM] [RadioRA2] ~DEVICE,77,81,9,1
[2/4/2024, 8:53:44 PM] [RadioRA2] ~DEVICE,104,82,9,0
[2/4/2024, 8:53:44 PM] [RadioRA2] ~DEVICE,105,83,9,0
[2/4/2024, 8:53:44 PM] [RadioRA2] ~DEVICE,116,82,9,0
[2/4/2024, 8:53:44 PM] [RadioRA2] ~DEVICE,120,82,9,1
[2/4/2024, 8:53:44 PM] [RadioRA2] PING!
[2/4/2024, 8:53:45 PM] [RadioRA2] PING!
[2/4/2024, 8:53:46 PM] [RadioRA2] PING!
[2/4/2024, 8:53:47 PM] [RadioRA2] PING!
[2/4/2024, 8:53:48 PM] [RadioRA2] PING!
[2/4/2024, 8:53:49 PM] [RadioRA2] PING!
[2/4/2024, 8:53:50 PM] [RadioRA2] PING!
[2/4/2024, 8:53:51 PM] [RadioRA2] ~DEVICE,104,2,3
[2/4/2024, 8:53:51 PM] [RadioRA2] ~ADDRESS,0x0148AEE1
[2/4/2024, 8:53:51 PM] [RadioRA2] Preset ID:     40fa does not pertain to a device on link 0. Do nothing
[2/4/2024, 8:53:51 PM] [RadioRA2] ~OUTPUT,98,1,100.00
[2/4/2024, 8:53:51 PM] [RadioRA2] ~OUTPUT,98,29,8
[2/4/2024, 8:53:51 PM] [RadioRA2] ~OUTPUT,98,30,1,100.00
[2/4/2024, 8:53:51 PM] [RadioRA2] ~OUTPUT,99,1,100.00
[2/4/2024, 8:53:51 PM] [RadioRA2] ~OUTPUT,99,29,8
[2/4/2024, 8:53:51 PM] [RadioRA2] ~OUTPUT,99,30,1,100.00
[2/4/2024, 8:53:51 PM] [RadioRA2] ~DEVICE,104,82,9,1
[2/4/2024, 8:53:51 PM] [RadioRA2] ~DEVICE,77,81,9,0
[2/4/2024, 8:53:51 PM] [RadioRA2] ~DEVICE,105,83,9,1
[2/4/2024, 8:53:51 PM] [RadioRA2] ~DEVICE,116,82,9,1
[2/4/2024, 8:53:51 PM] [RadioRA2] ~DEVICE,120,82,9,0
[2/4/2024, 8:53:51 PM] [RadioRA2] ~DEVICE,104,2,3
[2/4/2024, 8:53:51 PM] [RadioRA2] ~ADDRESS,0x0148AEE1
[2/4/2024, 8:53:51 PM] [RadioRA2] Preset ID:     40fa does not pertain to a device on link 0. Do nothing
[2/4/2024, 8:53:51 PM] [RadioRA2] ~OUTPUT,98,1,0.00
[2/4/2024, 8:53:51 PM] [RadioRA2] ~OUTPUT,98,29,8
[2/4/2024, 8:53:51 PM] [RadioRA2] ~OUTPUT,98,30,1,0.00
[2/4/2024, 8:53:51 PM] [RadioRA2] PING!
[2/4/2024, 8:53:52 PM] [RadioRA2] ~OUTPUT,99,1,0.00
[2/4/2024, 8:53:52 PM] [RadioRA2] ~OUTPUT,99,29,8
[2/4/2024, 8:53:52 PM] [RadioRA2] ~OUTPUT,99,30,1,0.00
[2/4/2024, 8:53:52 PM] [RadioRA2] ~DEVICE,104,82,9,0
[2/4/2024, 8:53:52 PM] [RadioRA2] ~DEVICE,105,83,9,0
[2/4/2024, 8:53:52 PM] [RadioRA2] ~DEVICE,116,82,9,0
[2/4/2024, 8:53:52 PM] [RadioRA2] ~OUTPUT,127,1,0.00
[2/4/2024, 8:53:52 PM] [RadioRA2] ~OUTPUT,127,29,8
[2/4/2024, 8:53:52 PM] [RadioRA2] ~OUTPUT,127,30,1,0.00
[2/4/2024, 8:53:52 PM] [RadioRA2] PING!
[2/4/2024, 8:53:53 PM] [RadioRA2] PING!
[2/4/2024, 8:53:54 PM] [RadioRA2] PING!
[2/4/2024, 8:53:55 PM] [RadioRA2] PING!
[2/4/2024, 8:53:57 PM] [RadioRA2] PING!
[2/4/2024, 8:53:58 PM] [RadioRA2] PING!
[2/4/2024, 8:53:59 PM] [RadioRA2] PING!

**Comment by senorshaun** [comment]
that error means its pulling back a Mal-formed xml or the xml2js module isn't able to parse it properly. No it should take about 15 seconds to pull back and process devices.

I dont have anything in the plugin that writes out PING! every second. So I dont know where that is coming from. I also don't have anything that would output the line "Preset ID: 40fa does not pertain to a device on link 0. Do nothing". Do you have multiple radiora2 plugins installed?

If so, try removing all of them. and then installing this one to make sure its clean

**Comment by oxide7** [comment]
the ping only comes out when i have all your debug options on. i deleted the plugin an resintalled, and then tried wihtout the verbose debug options and this came out:

[2/4/2024, 9:38:15 PM] [Homebridge UI] [homebridge-radiora2] TypeError: areas.hasOwnProperty is not a function
    at UiServer.processAreas (/homebridge/node_modules/homebridge-radiora2/homebridge-ui/server.js:27:14)
    at /homebridge/node_modules/homebridge-radiora2/homebridge-ui/server.js:245:64
    at Array.map (<anonymous>)
    at UiServer.getAllDevices (/homebridge/node_modules/homebridge-radiora2/homebridge-ui/server.js:245:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UiServer.processRequest (/homebridge/node_modules/homebridge-radiora2/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)

**Comment by oxide7** [comment]
Incredible!! It works now. Didn't find my windows but that's ok -- will use the bridge for that. Thank you so much! Will play with it and let you know if any issues

[2/13/2024, 12:48:01 PM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 3C5E) is running on port 51547.
[2/13/2024, 12:48:01 PM] [RadioRA2] Logged in to RadioRA2 Main Repeater at 10.0.0.180
[2/13/2024, 12:48:01 PM] [RadioRA2] Loaded 1 fan(s)
[2/13/2024, 12:48:01 PM] [RadioRA2] Loaded 77 light(s)
[2/13/2024, 12:48:01 PM] [RadioRA2] Loaded 0 occupancy sensor(s)
[2/13/2024, 12:48:02 PM] [RadioRA2] Loaded 21 keypad(s)
[2/13/2024, 12:48:02 PM] [RadioRA2] Loaded 0 visor control reciever(s)
[2/13/2024, 12:48:02 PM] [RadioRA2] Loaded 6 hvac controller(s)
[2/13/2024, 12:48:02 PM] [RadioRA2] Loaded 0 window covering(s)

**Comment by senorshaun** [comment]
Thanks for letting me know. It was finding them, just not adding them to your config (same or visor control receivers). Update to 1.7.7 and try to auto-discover again to get them added
